---
name: 'tf-comment'

on:  # yamllint disable-line rule:truthy
  issue_comment:
    types: [created]

jobs:
  init:
    if: |
      github.event.comment.user.login != 'renovate[bot]' &&
      github.event.comment.user.login != 'terraformautomation[bot]'

    uses: arvatoaws-labs/github-actions-aws-terraform/.github/workflows/read-config.yml@v2

  tf-plan:
    # Required permissions
    permissions:
      actions: read
      id-token: write
      contents: read
      pull-requests: write

    needs: init

    strategy:
      matrix: 
        account: ${{ fromJSON(needs.init.outputs.accounts) }}
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/plan') }}
    uses: arvatoaws-labs/github-actions-aws-terraform/.github/workflows/githubaction-comment-plan.yml@v2
    with:
      stack: ${{ matrix.account.stack }}
      region: ${{ matrix.account.region }}
      roleArn: ${{ matrix.account.roleArn }}
      profiles: ${{ needs.init.outputs.profiles }}
      environment: ${{ matrix.account.environment }}
      execute: ${{ contains(github.event.issue.labels.*.name, format('terraform-{0}-changed', matrix.account.stack) ) }}
      s3bucketName: ${{ matrix.account.s3bucketName }}
      github_event_number: ${{ github.event.issue.number }}
      github_event_issue_comments_url: ${{ github.event.issue.comments_url }}
    secrets: inherit

  tf-apply:
    # Required permissions
    permissions:
      actions: read
      id-token: write
      contents: write
      pull-requests: write

    needs: init

    strategy:
      matrix: 
        account: ${{ fromJSON(needs.init.outputs.accounts) }}
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/apply') }}
    uses: arvatoaws-labs/github-actions-aws-terraform/.github/workflows/githubaction-comment-apply.yml@v2
    with:
      stack: ${{ matrix.account.stack }}
      region: ${{ matrix.account.region }}
      roleArn: ${{ matrix.account.roleArn }}
      profiles: ${{ needs.init.outputs.profiles }}
      environment: ${{ matrix.account.environment }}
      execute: ${{ contains(github.event.issue.labels.*.name, format('terraform-{0}-changed', matrix.account.stack) ) && contains(github.event.issue.labels.*.name, format('terraform-{0}-planned', matrix.account.stack) ) }}
      s3bucketName: ${{ matrix.account.s3bucketName }}
      github_event_number: ${{ github.event.issue.number }}
      github_event_issue_comments_url: ${{ github.event.issue.comments_url }}
      github_event_repository_url: ${{ github.event.repository.url }}
      do_merge_on_success: true
    secrets: inherit