name: 'TofuPlan'

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      roleArn:
        required: true
        type: string
      s3bucketName:
        required: true
        type: string
      github_event_number:
        required: true
        type: string
      github_event_issue_comments_url:
        required: true
        type: string
      stack:
        required: false
        type: string
        default: "."
      environment:
        required: false
        type: string
        default: "none"
      execute:
        required: true
        type: boolean
        default: false
jobs:
  tofu:
    name: 'Plan Tofu'
    runs-on: arvato
    permissions:
      actions: read
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        shell: bash
    if: ${{ inputs.execute == true }}

    steps:
    - name: Initialize Error Log
      run: touch error_log.txt

    # Assume the role in AWS to roll out the changes
    - name: Configure AWS Credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.roleArn }}
        role-session-name: GitHubTerraformDeployment

    # Get the github token with access to the relevant repositories from the app
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ secrets.TERRAFORM_GITHUB_ACTION_APP_ID }}
        private-key: ${{ secrets.TERRAFORM_GITHUB_ACTION_PRIVATE_KEY }}
        owner: arvatoaws

    # Configure github access
    - uses: de-vri-es/setup-git-credentials@v2
      id: configure-git-credentials
      with:
        credentials: https://oauth:${{ steps.generate-token.outputs.token }}@github.com/

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      id: checkout-pull-request
      uses: actions/checkout@v6
      with:
        ref: refs/pull/${{ inputs.github_event_number }}/merge
        fetch-depth: 0

    - name: Check branch status (on pull request)
      if: github.event_name == 'pull_request'
      run: |
        set -x
        TIMESTAMP=`date "+%Y-%m-%d %H:%M:%S"`
        
        # Fetch the base branch (e.g., main)
        git fetch origin ${{ github.base_ref }}
        
        # Find the latest commit on the base branch
        BASE_SHA=$(git rev-parse origin/${{ github.base_ref }})
        
        # Find the common ancestor (merge base) between the PR and the Base
        MERGE_BASE=$(git merge-base HEAD origin/${{ github.base_ref }})
        
        if [ "$BASE_SHA" = "$MERGE_BASE" ]; then
          echo "Branch is up to date."
          echo "is_outdated=false" >> $GITHUB_OUTPUT
        else
          echo "$TIMESTAMP: PR branch is out of date with $BASE_BRANCH - **${{ inputs.stack }}** (env: ${{ inputs.environment }})" >> error_log.txt

          echo "is_outdated=true" >> $GITHUB_OUTPUT
          exit 1 # Fail the step if it's out of date
        fi

    - name: Check branch status (on issue comment)
      if: github.event.issue.pull_request
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        set -x
        TIMESTAMP=`date "+%Y-%m-%d %H:%M:%S"`

        # 1. Get branch info via GitHub CLI
        PR_DATA=$(gh pr view ${{ github.event.issue.number }} --json baseRefName,headRefName)
        BASE_BRANCH=$(echo $PR_DATA | jq -r '.baseRefName')
        HEAD_BRANCH=$(echo $PR_DATA | jq -r '.headRefName')

        echo "Comparing $HEAD_BRANCH against $BASE_BRANCH"

        # 2. Fetch both branches explicitly
        git fetch origin $BASE_BRANCH:$BASE_BRANCH
        git fetch origin $HEAD_BRANCH:$HEAD_BRANCH

        # 3. Compare
        BASE_SHA=$(git rev-parse $BASE_BRANCH)
        MERGE_BASE=$(git merge-base $HEAD_BRANCH $BASE_BRANCH)

        if [ "$BASE_SHA" != "$MERGE_BASE" ]; then
          echo "$TIMESTAMP: PR branch is out of date with $BASE_BRANCH - **${{ inputs.stack }}** (env: ${{ inputs.environment }})" >> error_log.txt

          echo "::error::PR branch is out of date with $BASE_BRANCH"
          exit 1
        else
          echo "PR is up to date!"
        fi

    - name: Reading Terraform variables from GitHub Secrets
      id: read-github-secrets
      run: |
        SECRETS_JSON='${{ toJson(secrets) }}'
        SECRETS=$(echo "$SECRETS_JSON" | jq -r 'keys[]')
        # Loop over each secret in the GitHub Actions environment
        for key in $SECRETS; do
          value=$(echo "$SECRETS_JSON" | jq -r ".[\"$key\"]")
          # Check if the secret name has the prefix "TF_VAR_"
          if [[ $key == TF_VAR_* ]]; then
            # Add the secret as an input variable to the tofu command
            export "$key=$value"
            echo "${key#TF_VAR_} = \"$value\"" >> ${{ github.workspace }}/secret_variables.tfvars
          fi
        done
      shell: bash

    - name: terraform plan ${{ inputs.stack }}
      id: tfplan
      uses: dflook/tofu-plan@v2
      with:
        path: ${{ inputs.stack }}
        add_github_comment: always-new
        label: ${{ inputs.stack }} (${{ inputs.environment }})
        var_file: |
          secret_variables.tfvars
      env:
        OPENTOFU_VERSION: 1.11.5
        TF_PLAN_COLLAPSE_LENGTH: 1000  # Set this high to keep it expanded
        TERRAFORM_HTTP_CREDENTIALS: |
          github.com/arvatoaws=oauth:${{ steps.generate-token.outputs.token }}
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        GITHUB_APP_ID: ${{ secrets.TERRAFORM_GITHUB_ACTION_APP_ID }}
        GITHUB_APP_PEM_FILE: ${{ secrets.TERRAFORM_GITHUB_ACTION_PRIVATE_KEY }}
        TERRAFORM_PRE_RUN: |
          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
          unzip -qq awscliv2.zip
          ./aws/install
          /usr/local/bin/aws --version

    - name: Add Successful labels to GitHub PR
      id: add-success-labels-to-pull-request

      if: success()
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        set -x
        TIMESTAMP=`date "+%Y-%m-%d %H:%M:%S"`

        gh pr edit ${{ inputs.github_event_number }} --remove-label "terraform-${{ inputs.stack }}-failed"

        gh label create "terraform-${{ inputs.stack }}-planned" --color "008000" --force
        gh pr edit ${{ inputs.github_event_number }} --add-label "terraform-${{ inputs.stack }}-planned"

        if [ "${{ steps.tfplan.outputs.changes }}" == "false" ] 
          then
            gh label create "terraform-${{ inputs.stack }}-plan-no_changes" --force
            gh pr edit ${{ inputs.github_event_number }} --add-label "terraform-${{ inputs.stack }}-plan-no_changes"
        fi
        
        echo "$TIMESTAMP: Tofu plan successful on **${{ inputs.stack }}** (env: ${{ inputs.environment }})" >> error_log.txt

    - name: Add Failed labels to GitHub PR
      id: add-failed-labels-to-pull-request
      if: failure()
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        set -x
        TIMESTAMP=`date "+%Y-%m-%d %H:%M:%S"`

        gh label create "terraform-${{ inputs.stack }}-failed" --color "ff0000" --force
        gh pr edit ${{ inputs.github_event_number }} --add-label "terraform-${{ inputs.stack }}-failed"

        echo "$TIMESTAMP: Tofu plan failed on **${{ inputs.stack }}** (env: ${{ inputs.environment }})" >> error_log.txt

    - name: Report Results
      if: always()
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        if [ -s error_log.txt ]; then
          gh pr comment ${{ inputs.github_event_number }} --body-file error_log.txt --repo ${{ github.repository }}
        fi