name: 'TofuScheduledDrift'

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      roleArn:
        required: true
        type: string
      stack:
        required: false
        type: string
        default: "."
      environment:
        required: false
        type: string
        default: "none"
      execute:
        required: true
        type: boolean
        default: false

jobs:
  tofu:
    name: 'Drift Tofu'
    runs-on: arvato
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        shell: bash
    if: ${{ inputs.execute == true }}

    steps:
    # Assume the role in AWS to roll out the changes
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.roleArn }}

    # Get the github token with access to the relevant repositories from the app
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ secrets.TERRAFORM_GITHUB_ACTION_APP_ID }}
        private-key: ${{ secrets.TERRAFORM_GITHUB_ACTION_PRIVATE_KEY }}
        owner: arvatoaws

    # Configure github access
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://oauth:${{ steps.generate-token.outputs.token }}@github.com/

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v6
  
    - name: Reading Terraform variables from GitHub Secrets
      run: |
        SECRETS_JSON='${{ toJson(secrets) }}'
        SECRETS=$(echo "$SECRETS_JSON" | jq -r 'keys[]')
        # Loop over each secret in the GitHub Actions environment
        for key in $SECRETS; do
          value=$(echo "$SECRETS_JSON" | jq -r ".[\"$key\"]")
          # Check if the secret name has the prefix "TF_VAR_"
          if [[ $key == TF_VAR_* ]]; then
            # Add the secret as an input variable to the tofu command
            export "$key=$value"
            echo "${key#TF_VAR_} = \"$value\"" >> ${{ github.workspace }}/secret_variables.tfvars
          fi
        done
      shell: bash

    - name: terraform check ${{ inputs.stack }}
      id: check
      uses: dflook/tofu-check@v2
      with:
        path: ${{ inputs.stack }}
        var_file: |
          secret_variables.tfvars
      env:
        OPENTOFU_VERSION: 1.11.5
        TERRAFORM_HTTP_CREDENTIALS: |
          github.com/arvatoaws=oauth:${{ steps.generate-token.outputs.token }}
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        GITHUB_APP_ID: ${{ secrets.TERRAFORM_GITHUB_ACTION_APP_ID }}
        GITHUB_APP_PEM_FILE: ${{ secrets.TERRAFORM_GITHUB_ACTION_PRIVATE_KEY }}
        TERRAFORM_PRE_RUN: |
          # Install AWS CLI for X86
          curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          ./aws/install
          /usr/local/bin/aws --version

    - name: Changes detected
      if: ${{ failure() && steps.check.outputs.failure-reason == 'changes-to-apply' }}
      run: echo "IaC code does not match current infrastructure. Please apply changes."

    - name: Check failed
      if: ${{ failure() && steps.check.outputs.failure-reason != 'changes-to-apply' }}
      run: echo "Drift check failed."