name: 'TofuPlan'

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      roleArn:
        required: true
        type: string
      s3bucketName:
        required: true
        type: string
      github_event_number:
        required: true
        type: string
      github_event_issue_comments_url:
        required: true
        type: string
      stack:
        required: false
        type: string
        default: "."
      environment:
        required: false
        type: string
        default: "none"
      execute:
        required: true
        type: boolean
        default: false
jobs:
  tofu:
    name: 'Plan Tofu'
    runs-on: arvato
    permissions:
      actions: read
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        shell: bash
    if: ${{ inputs.execute == true }}

    steps:
    # Assume the role in AWS to roll out the changes
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.roleArn }}
        role-session-name: GitHubTerraformDeployment

    # Get the github token with access to the relevant repositories from the app
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ secrets.TERRAFORM_GITHUB_ACTION_APP_ID }}
        private-key: ${{ secrets.TERRAFORM_GITHUB_ACTION_PRIVATE_KEY }}
        owner: arvatoaws

    # Configure github access
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://oauth:${{ steps.generate-token.outputs.token }}@github.com/

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: refs/pull/${{ inputs.github_event_number }}/merge

    - name: Reading Repository name
      run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      shell: bash

    - name: Reading Terraform variables from GitHub Secrets
      run: |
        SECRETS_JSON='${{ toJson(secrets) }}'
        SECRETS=$(echo "$SECRETS_JSON" | jq -r 'keys[]')
        # Loop over each secret in the GitHub Actions environment
        for key in $SECRETS; do
          value=$(echo "$SECRETS_JSON" | jq -r ".[\"$key\"]")
          # Check if the secret name has the prefix "TF_VAR_"
          if [[ $key == TF_VAR_* ]]; then
            # Add the secret as an input variable to the tofu command
            export "$key=$value"
            echo "${key#TF_VAR_} = \"$value\"" >> ${{ github.workspace }}/secret_variables.tfvars
          fi
        done
      shell: bash

    - name: terraform plan ${{ inputs.stack }}
      id: tfplan
      uses: dflook/tofu-plan@v2
      with:
        path: ${{ inputs.stack }}
        add_github_comment: always-new
        label: ${{ inputs.environment }}
        var_file: |
          secret_variables.tfvars
      env:
        OPENTOFU_VERSION: 1.11.5
        TERRAFORM_HTTP_CREDENTIALS: |
          github.com/arvatoaws=oauth:${{ steps.generate-token.outputs.token }}
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        GITHUB_APP_ID: ${{ secrets.TERRAFORM_GITHUB_ACTION_APP_ID }}
        GITHUB_APP_PEM_FILE: ${{ secrets.TERRAFORM_GITHUB_ACTION_PRIVATE_KEY }}
        TERRAFORM_PRE_RUN: |
          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
          unzip -qq awscliv2.zip
          ./aws/install
          /usr/local/bin/aws --version

    - name: Add Successful labels to GitHub PR
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        TIMESTAMP=`date "+%Y-%m-%d %H:%M:%S"`

        labels=("terraform-${{ inputs.environment }}-planned")
        
        labels_final="$(jq --compact-output --null-input '$ARGS.positional' --args -- "${labels[@]}")"
        echo "Final labels: ${labels_final}"

        echo "changes: ${{ steps.tfplan.outputs.changes }}"
        if [ "${{ steps.tfplan.outputs.changes }}" == "false" ] 
          then
            labels+=("terraform-${{ inputs.environment }}-plan-no_changes")
        fi

        curl \
          -X POST \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.github_event_number }}/labels \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"labels\": $labels_final}"
        
        gh pr comment ${{ inputs.github_event_number }} --body "$TIMESTAMP: Tofu plan successful on ${{ inputs.environment }}" --repo ${{ github.repository }}

    - name: Add Failed labels to GitHub PR
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        TIMESTAMP=`date "+%Y-%m-%d %H:%M:%S"`

        labels=("terraform-${{ inputs.environment }}-plan_failed")
        
        labels_final="$(jq --compact-output --null-input '$ARGS.positional' --args -- "${labels[@]}")"
        echo "Final labels: ${labels_final}"

        curl \
          -X POST \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.github_event_number }}/labels \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"labels\": $labels_final}"

        gh pr comment ${{ inputs.github_event_number }} --body "$TIMESTAMP: Tofu plan failed on stack: ${{ inputs.stack }}, env: ${{ inputs.environment }}" --repo ${{ github.repository }}