name: Read Config

on:
  workflow_call:
    inputs:
      config_file:
        type: string
        default: .github/config.yaml
    outputs:
      config_data:
        description: "The YAML content of the config file"
        value: ${{ jobs.read-repo-config.outputs.config_data }}
      accounts:
        value: ${{ jobs.read-repo-config.outputs.accounts }}
      stacks:
        value: ${{ jobs.read-repo-config.outputs.stacks }}
      pr-labels:
        value: ${{ jobs.read-repo-config.outputs.labels }}

jobs:
  read-repo-config:

    permissions:
      actions: read
      id-token: write
      contents: read
      pull-requests: write

    runs-on: arvato

    outputs:
      config_data: ${{ steps.read-yaml.outputs.config_data }}
      accounts: ${{ steps.read-yaml.outputs.accounts }}
      stacks: ${{ steps.read-yaml.outputs.stacks }}
      pr-labels: ${{ steps.get-pr-labels.outputs.labels }}

    steps:
      - uses: actions/checkout@v6

      - name: Read YAML
        id: read-yaml

        run: |
          if [[ -f "${{ inputs.config_file }}" ]]; then
              # Validate JSON
              if yq eval '.' ${{ inputs.config_file }} > /dev/null 2>&1; then

                result=$(yq -o=json -I=0 '.include = .accounts | del(.accounts)' ${{ inputs.config_file }})
                  # Use a heredoc to handle potential multiline data safely
                  {
                    echo "config_data<<EOF"
                    echo "$result"
                    echo "EOF"
                  } >> "$GITHUB_OUTPUT"

                  result=$(yq -o=json -I=0 '.accounts = .accounts' ${{ inputs.config_file }})
                  {
                    echo "accounts<<EOF"
                    echo "$result"
                    echo "EOF"
                  } >> "$GITHUB_OUTPUT"

                  result=$(yq -o=json -I=0 '[.accounts[].stack]' ${{ inputs.config_file }})
                  {
                    echo "stacks<<EOF"
                    echo "$result"
                    echo "EOF"
                  } >> "$GITHUB_OUTPUT"
                  
                  echo "Successfully wrote config to GITHUB_OUTPUT"
              else
                  echo "Error: ${{ inputs.config_file }} contains invalid YAML"
                  exit 1
              fi
          else
              echo "Error: ${{ inputs.config_file }} not found"
              exit 1
          fi
      - name: read PR labels
        id: get-pr-labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "labels"=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number || github.event.pull_request.number }} | jq '.labels | map( .name ) | join ( "," )')
          echo "labels"=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number || github.event.pull_request.number }} | jq '.labels | map( .name ) | join ( "," )') >> $GITHUB_OUTPUT